import hashlib
import json


def md5(s: str) -> str:
    return hashlib.md5(s.strip().lower().encode()).hexdigest()


def get_username(email: str) -> str:
    return email.split("@")[0]


PLATFORMS = [

    {
        "name": "Facebook",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.facebook.com/ajax/login/help/identify.php",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-Requested-With": "XMLHttpRequest",
            "Referer": "https://www.facebook.com/login/identify",
        },
        "data": lambda e: f"email={e}&did_logout=0&save=&next=",
        "check": "keyword_missing",
        "keyword": "no_account_found",
    },
    {
        "name": "Twitter / X",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://x.com/i/flow/password_reset",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "Referer": "https://x.com/",
        },
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "We couldn't find",
    },
    {
        "name": "Instagram",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.instagram.com/accounts/account_recovery_send_ajax/",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-Requested-With": "XMLHttpRequest",
            "Referer": "https://www.instagram.com/",
        },
        "data": lambda e: f"email_or_username={e}",
        "check": "keyword_found",
        "keyword": "email_found",
    },
    {
        "name": "TikTok",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.tiktok.com/passport/web/account/forgot/",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "Referer": "https://www.tiktok.com/",
        },
        "data": lambda e: f"email={e}&type=email&platform=web",
        "check": "keyword_missing",
        "keyword": "USER_NOT_FOUND",
    },
    {
        "name": "Snapchat",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://accounts.snapchat.com/accounts/password_reset_email",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "Pinterest",
        "category": "Social",
        "method": "GET",
        "url_fn": lambda e: (
            "https://www.pinterest.com/resource/EmailExistsResource/get/"
            f"?source_url=%2F&data=%7B%22options%22%3A%7B%22email%22%3A%22{e}%22%7D%7D"
        ),
        "check": "keyword_found",
        "keyword": '"data": true',
    },
    {
        "name": "Reddit",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.reddit.com/api/v1/password_reset",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "USER_DOESNT_EXIST",
    },
    {
        "name": "Tumblr",
        "category": "Social",
        "method": "GET",
        "url_fn": lambda e: f"https://www.tumblr.com/api/v2/user/check_email?email={e}",
        "check": "keyword_found",
        "keyword": '"exists":true',
    },
    {
        "name": "VK",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://vk.com/login",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}&act=forgot_pass",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Flickr",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://identity.flickr.com/sign-in",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "Foursquare",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://foursquare.com/forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "We couldn't find",
    },
    {
        "name": "Quora",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.quora.com/",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "We couldn't find",
    },
    {
        "name": "Meetup",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://secure.meetup.com/forgot_password/",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Mastodon",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://mastodon.social/auth/password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"user[email]={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Minds",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://www.minds.com/api/v1/forgotpassword/request",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"username": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "MeWe",
        "category": "Social",
        "method": "POST",
        "url_fn": lambda e: "https://mewe.com/api/v3/auth/password-reset",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "GitHub",
        "category": "Tech",
        "method": "POST",
        "url_fn": lambda e: "https://github.com/account/password_reset",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "Referer": "https://github.com/password_reset",
        },
        "data": lambda e: f"email={e}",
        "check": "keyword_found",
        "keyword": "If your email address exists in our database",
    },
    {
        "name": "GitLab",
        "category": "Tech",
        "method": "POST",
        "url_fn": lambda e: "https://gitlab.com/users/password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"user[email]={e}",
        "check": "keyword_found",
        "keyword": "If your email address exists",
    },
    {
        "name": "Gravatar",
        "category": "Tech",
        "method": "GET",
        "url_fn": lambda e: f"https://www.gravatar.com/{md5(e)}.json",
        "check": "status_ok",
        "ok_status": [200],
        "username_re": r'"preferredUsername"\s*:\s*"([^"]+)"',
    },
    {
        "name": "Codecademy",
        "category": "Tech",
        "method": "GET",
        "url_fn": lambda e: f"https://www.codecademy.com/api/v1/registration_validations?user%5Bemail%5D={e}",
        "check": "keyword_found",
        "keyword": '"taken":true',
    },
    {
        "name": "HackerNews",
        "category": "Tech",
        "method": "GET",
        "url_fn": lambda e: f"https://hacker-news.firebaseio.com/v0/user/{get_username(e)}.json",
        "check": "keyword_found",
        "keyword": '"id"',
        "username_re": r'"id"\s*:\s*"([^"]+)"',
    },
    {
        "name": "Stack Overflow",
        "category": "Tech",
        "method": "POST",
        "url_fn": lambda e: "https://stackoverflow.com/users/account-recovery",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "Bitbucket",
        "category": "Tech",
        "method": "POST",
        "url_fn": lambda e: "https://bitbucket.org/account/password/reset/",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "npm",
        "category": "Tech",
        "method": "POST",
        "url_fn": lambda e: "https://www.npmjs.com/forgot",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "LinkedIn",
        "category": "Professional",
        "method": "POST",
        "url_fn": lambda e: "https://www.linkedin.com/uas/request-password-reset",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "email address is not associated",
    },
    {
        "name": "Xing",
        "category": "Professional",
        "method": "POST",
        "url_fn": lambda e: "https://www.xing.com/app/user?op=forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Freelancer",
        "category": "Professional",
        "method": "GET",
        "url_fn": lambda e: f"https://www.freelancer.com/ajax/checkuser.php?email={e}",
        "check": "keyword_found",
        "keyword": '"status":"taken"',
    },
    {
        "name": "Upwork",
        "category": "Professional",
        "method": "POST",
        "url_fn": lambda e: "https://www.upwork.com/ab/account-security/forgot-password",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"login": e}),
        "check": "keyword_missing",
        "keyword": "No account",
    },
    {
        "name": "Fiverr",
        "category": "Professional",
        "method": "POST",
        "url_fn": lambda e: "https://www.fiverr.com/users/password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email_or_username={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "Twitch",
        "category": "Gaming",
        "method": "GET",
        "url_fn": lambda e: f"https://passport.twitch.tv/register/check_available?email={e}",
        "check": "keyword_found",
        "keyword": '"isAvailable":false',
    },
    {
        "name": "Steam",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://store.steampowered.com/join/checkavail/",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "Referer": "https://store.steampowered.com/join/",
        },
        "data": lambda e: f"accountname=doesnotmatter&email={e}&count=1",
        "check": "keyword_found",
        "keyword": '"bAvail":false',
    },
    {
        "name": "Epic Games",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://www.epicgames.com/id/api/v2/password/forgot/init",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "account_not_found",
    },
    {
        "name": "Roblox",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://auth.roblox.com/v2/passwords/forgot",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "status_ok",
        "ok_status": [200],
    },
    {
        "name": "Ubisoft",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://account.ubisoft.com/api/users/forgot-password",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"nameOnPlatform": e, "platformType": "uplay"}),
        "check": "keyword_missing",
        "keyword": "accountNotFound",
    },
    {
        "name": "EA / Origin",
        "category": "Gaming",
        "method": "GET",
        "url_fn": lambda e: f"https://signin.ea.com/p/ajax/user/checkEmailStatus?email={e}",
        "check": "keyword_found",
        "keyword": '"status":"EXISTS"',
    },
    {
        "name": "Battle.net",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://us.battle.net/login/en/?ref=localhost",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"accountName={e}&password=wrong",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "PlayStation",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://my.account.sony.com/api/v1/ssocookie",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"loginId={e}&password=wrong",
        "check": "keyword_missing",
        "keyword": "accountNotFound",
    },
    {
        "name": "Xbox / Microsoft",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://login.live.com/GetCredentialType.srf",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"username": e, "uaid": "", "isOtherIdpSupported": True}),
        "check": "keyword_found",
        "keyword": '"IfExistsResult":0',
    },
    {
        "name": "Minecraft",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://authserver.mojang.com/authenticate",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"agent": {"name": "Minecraft", "version": 1},
                                      "username": e, "password": "wrong"}),
        "check": "keyword_missing",
        "keyword": "FORBIDDEN",
    },
    {
        "name": "GOG",
        "category": "Gaming",
        "method": "POST",
        "url_fn": lambda e: "https://login.gog.com/login_check",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"login[username]={e}&login[password]=wrongpassword",
        "check": "keyword_missing",
        "keyword": "Username not found",
    },

    {
        "name": "Spotify",
        "category": "Music",
        "method": "POST",
        "url_fn": lambda e: "https://spclient.wg.spotify.com/signup/public/v1/account",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"validate=1&email={e}",
        "check": "keyword_found",
        "keyword": '"status":20',
    },
    {
        "name": "SoundCloud",
        "category": "Music",
        "method": "GET",
        "url_fn": lambda e: f"https://soundcloud.com/users/email_available?email={e}",
        "check": "keyword_found",
        "keyword": '"exists":true',
    },
    {
        "name": "Last.fm",
        "category": "Music",
        "method": "POST",
        "url_fn": lambda e: "https://www.last.fm/user/forgotpassword",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"username_or_email={e}",
        "check": "keyword_missing",
        "keyword": "We couldn't find",
    },
    {
        "name": "Deezer",
        "category": "Music",
        "method": "POST",
        "url_fn": lambda e: "https://www.deezer.com/ajax/action.php",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"method=User.checkEmail&mail={e}",
        "check": "keyword_found",
        "keyword": '"ALREADY_USED"',
    },
    {
        "name": "Apple Music",
        "category": "Music",
        "method": "POST",
        "url_fn": lambda e: "https://appleid.apple.com/auth/validate/appleid",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"appleId={e}&accountExists=1",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Bandcamp",
        "category": "Music",
        "method": "POST",
        "url_fn": lambda e: "https://bandcamp.com/login",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"username={e}&password=wrongpassword",
        "check": "keyword_missing",
        "keyword": "There's no account",
    },

    {
        "name": "YouTube",
        "category": "Video",
        "method": "POST",
        "url_fn": lambda e: "https://accounts.google.com/_/signin/sl/lookup",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"Email={e}&lookup=1",
        "check": "keyword_missing",
        "keyword": "LOOKUP_FAILED",
    },
    {
        "name": "Vimeo",
        "category": "Video",
        "method": "POST",
        "url_fn": lambda e: "https://vimeo.com/forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Dailymotion",
        "category": "Video",
        "method": "POST",
        "url_fn": lambda e: "https://www.dailymotion.com/user/forgotpassword",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Twitch (Video)",
        "category": "Video",
        "method": "GET",
        "url_fn": lambda e: f"https://passport.twitch.tv/register/check_available?email={e}",
        "check": "keyword_found",
        "keyword": '"isAvailable":false',
    },

    {
        "name": "Discord",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://discord.com/api/v9/auth/forgot",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"login": e}),
        "check": "status_ok",
        "ok_status": [200],
    },
    {
        "name": "Skype",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://login.live.com/GetCredentialType.srf",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"username": e}),
        "check": "keyword_found",
        "keyword": '"IfExistsResult":0',
    },
    {
        "name": "Zoom",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://zoom.us/forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "did not find",
    },
    {
        "name": "Slack",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://slack.com/forgot",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Telegram",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://my.telegram.org/auth/send_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"phone={e}",
        "check": "keyword_missing",
        "keyword": "error",
    },
    {
        "name": "Signal",
        "category": "Communication",
        "method": "GET",
        "url_fn": lambda e: f"https://textsecure-service.whispersystems.org/v1/accounts/email/{e}",
        "check": "status_ok",
        "ok_status": [200, 401],
    },
    {
        "name": "Teams (Microsoft)",
        "category": "Communication",
        "method": "POST",
        "url_fn": lambda e: "https://login.microsoftonline.com/common/GetCredentialType",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"username": e, "isOtherIdpSupported": True}),
        "check": "keyword_found",
        "keyword": '"IfExistsResult":0',
    },

    {
        "name": "Dropbox",
        "category": "Cloud",
        "method": "POST",
        "url_fn": lambda e: "https://www.dropbox.com/forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"login_email={e}&t=",
        "check": "keyword_missing",
        "keyword": "There is no Dropbox account",
    },
    {
        "name": "Google Drive",
        "category": "Cloud",
        "method": "POST",
        "url_fn": lambda e: "https://accounts.google.com/_/signin/sl/lookup",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"Email={e}&lookup=1",
        "check": "keyword_missing",
        "keyword": "LOOKUP_FAILED",
    },
    {
        "name": "OneDrive",
        "category": "Cloud",
        "method": "POST",
        "url_fn": lambda e: "https://login.live.com/GetCredentialType.srf",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"username": e}),
        "check": "keyword_found",
        "keyword": '"IfExistsResult":0',
    },
    {
        "name": "iCloud",
        "category": "Cloud",
        "method": "POST",
        "url_fn": lambda e: "https://appleid.apple.com/auth/validate/appleid",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"appleId={e}&accountExists=1",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Box",
        "category": "Cloud",
        "method": "POST",
        "url_fn": lambda e: "https://account.box.com/login",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"login={e}&password=wrongpassword",
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "Notion",
        "category": "Productivity",
        "method": "POST",
        "url_fn": lambda e: "https://www.notion.so/api/v3/sendTemporaryPassword",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "user not found",
    },
    {
        "name": "Evernote",
        "category": "Productivity",
        "method": "POST",
        "url_fn": lambda e: "https://www.evernote.com/Registration.action",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}&incomplete=true",
        "check": "keyword_found",
        "keyword": "already registered",
    },
    {
        "name": "Trello",
        "category": "Productivity",
        "method": "GET",
        "url_fn": lambda e: f"https://trello.com/1/auth/forgot/?email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Asana",
        "category": "Productivity",
        "method": "POST",
        "url_fn": lambda e: "https://app.asana.com/-/account_verify_email",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"e={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Monday.com",
        "category": "Productivity",
        "method": "POST",
        "url_fn": lambda e: "https://auth.monday.com/users/password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"user[email]={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "PayPal",
        "category": "Finance",
        "method": "POST",
        "url_fn": lambda e: "https://www.paypal.com/auth/validateEmail",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_found",
        "keyword": '"data":true',
    },
    {
        "name": "Coinbase",
        "category": "Finance",
        "method": "POST",
        "url_fn": lambda e: "https://www.coinbase.com/forgot-password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account",
    },
    {
        "name": "Binance",
        "category": "Finance",
        "method": "POST",
        "url_fn": lambda e: "https://accounts.binance.com/en/forgot-password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "User not found",
    },
    {
        "name": "Kraken",
        "category": "Finance",
        "method": "POST",
        "url_fn": lambda e: "https://www.kraken.com/u/recovery",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Revolut",
        "category": "Finance",
        "method": "POST",
        "url_fn": lambda e: "https://app.revolut.com/api/retail/user/login",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"phone": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "Adobe",
        "category": "Creative",
        "method": "POST",
        "url_fn": lambda e: "https://ims-na1.adobelogin.com/ims/check/v1/token",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"client_id=adobedotcom2&username={e}",
        "check": "keyword_found",
        "keyword": "account_exists",
    },
    {
        "name": "Behance",
        "category": "Creative",
        "method": "GET",
        "url_fn": lambda e: f"https://www.behance.net/action/emailAvailable?email={e}",
        "check": "keyword_found",
        "keyword": '"available":false',
    },
    {
        "name": "DeviantArt",
        "category": "Creative",
        "method": "GET",
        "url_fn": lambda e: f"https://www.deviantart.com/_puppy/accounts/emailavailable?email={e}",
        "check": "keyword_found",
        "keyword": '"exists":true',
    },
    {
        "name": "Canva",
        "category": "Creative",
        "method": "POST",
        "url_fn": lambda e: "https://www.canva.com/_ajax/auth/check-email",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_found",
        "keyword": '"exists":true',
    },
    {
        "name": "500px",
        "category": "Creative",
        "method": "GET",
        "url_fn": lambda e: f"https://api.500px.com/v1/users/check_email_uniqueness?email={e}",
        "check": "keyword_found",
        "keyword": '"taken":true',
    },
    {
        "name": "Figma",
        "category": "Creative",
        "method": "POST",
        "url_fn": lambda e: "https://www.figma.com/api/user/reset_password",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },

    {
        "name": "Etsy",
        "category": "Shopping",
        "method": "GET",
        "url_fn": lambda e: f"https://www.etsy.com/api/v3/ajax/member/email-check?email={e}",
        "check": "keyword_found",
        "keyword": '"member_exists":true',
    },
    {
        "name": "eBay",
        "category": "Shopping",
        "method": "POST",
        "url_fn": lambda e: "https://reg.ebay.de/reg/PartialRegistration?siteid=77",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"Email={e}&js_check=1",
        "check": "keyword_missing",
        "keyword": "no account",
    },
    {
        "name": "Amazon",
        "category": "Shopping",
        "method": "POST",
        "url_fn": lambda e: "https://www.amazon.com/ap/forgotpassword/reverification",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "No account found",
    },
    {
        "name": "Shopify",
        "category": "Shopping",
        "method": "POST",
        "url_fn": lambda e: "https://accounts.shopify.com/lookup",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Airbnb",
        "category": "Travel",
        "method": "POST",
        "url_fn": lambda e: "https://www.airbnb.com/api/v2/authentications",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e, "type": "email"}),
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Booking.com",
        "category": "Travel",
        "method": "POST",
        "url_fn": lambda e: "https://account.booking.com/auth/oauth2/authorize",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"username={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Uber",
        "category": "Travel",
        "method": "POST",
        "url_fn": lambda e: "https://auth.uber.com/login/",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"user_mobile_no_or_email={e}",
        "check": "keyword_missing",
        "keyword": "account not found",
    },
    {
        "name": "Netflix",
        "category": "Streaming",
        "method": "POST",
        "url_fn": lambda e: "https://www.netflix.com/password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "sorry",
    },
    {
        "name": "Hulu",
        "category": "Streaming",
        "method": "POST",
        "url_fn": lambda e: "https://www.hulu.com/start/forgot_password",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "data": lambda e: f"email={e}",
        "check": "keyword_missing",
        "keyword": "not found",
    },
    {
        "name": "Disney+",
        "category": "Streaming",
        "method": "POST",
        "url_fn": lambda e: "https://www.disneyplus.com/identity/passwordreset/initiate",
        "headers": {"Content-Type": "application/json"},
        "data": lambda e: json.dumps({"email": e}),
        "check": "keyword_missing",
        "keyword": "not found",
    },
]
